version: 2.1

# Define the jobs we want to run for this project
jobs:

  build:
    docker:
      - image: circleci/openjdk:11-jdk
      
    steps:
      - checkout
      - run: echo "this is the build job"
      # git pull de la rama master del proyecto
      - run: git pull origin main
      # compilar el gradle
      - run: gradle build
      # ejecutar el jar
      - run: gradle jar

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: gradle test
  
  validate:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle check

  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvnw spring-boot:run
          
# Orchestrate our job run sequence
workflows:
  build_and_test_all:
    jobs:
      - build
      - test
      - validate
      - deploy
